### ISSUE TITLE
0.8.3-beta提示未适配

### ISSUE THREAD

**Issue by wjw48818** [lanyuanxiaoyao/Bools#1]
rt

**Comment by lanyuanxiaoyao** [comment]
> rt

我重新安装了一遍, 没有问题, 你是什么系统

**Comment by wjw48818** [comment]
![image](https://user-images.githubusercontent.com/16645873/66734021-3566a280-ee94-11e9-84be-15f94a1ee813.png)
![image](https://user-images.githubusercontent.com/16645873/66734035-3ef00a80-ee94-11e9-90c0-f555080e3a50.png)

**Comment by lanyuanxiaoyao** [comment]
特别说明: 由于不同的浏览器支持程度不同, 同一个功能不一定能在所有浏览器中都能实现.
特别说明2: 鉴于写到一半的时候听说官方准备推出 workflow, 像这种只是模拟一下快捷键, 打开一些网址的插件, 我也就不打算很上心了, 自己偶尔用用(我也只是想生成一下二维码图 chrome 少装个插件而已), 娱乐一下就好, 所以尽管为跨平台做了铺垫, 但是估计是不打算做其他平台的兼容了.

**Comment by lanyuanxiaoyao** [comment]
特别说明: 由于不同的浏览器支持程度不同, 同一个功能不一定能在所有浏览器中都能实现.
特别说明2: 鉴于写到一半的时候听说官方准备推出 workflow, 像这种只是模拟一下快捷键, 打开一些网址的插件, 我也就不打算很上心了, 自己偶尔用用(我也只是想生成一下二维码图 chrome 少装个插件而已), 娱乐一下就好, 所以尽管为跨平台做了铺垫, 但是估计是不打算做其他平台的兼容了.


 原始邮件 
发件人: wjw48818<notifications@github.com>
收件人: lanyuanxiaoyao/Bools<Bools@noreply.github.com>
抄送: Lanyuanxiaoyao<lanyuanxiaoyao@qq.com>; Comment<comment@noreply.github.com>
发送时间: 2019年10月14日(周一) 15:06
主题: Re: [lanyuanxiaoyao/Bools] 0.8.3-beta提示未适配 (#1)
